### ISSUE TITLE
corrigir responsividade para mobile

### ISSUE THREAD

**Issue by wesleyallanwork** [wesleyallan/currency-converter#1]
# 🌐 Device
- Desktop
- OS: Windows 11
- Browser: Edge
- Browser Version: 111.0.1661.39

# ❌ Erro
Ao abrir em um dispositivo mobile ou simular o mesmo, o layout se encontra quebrado.

# 🔧 Correção
Que possua responsividade para mobile.

**Comment by wesleyallan** [comment]
# 🔎 Analyze
Adicionar _media queries_ para responsividade.
