### ISSUE TITLE
corrigir gráfico com histórico

### ISSUE THREAD

**Issue by wesleyallanwork** [wesleyallan/currency-converter#4]
# 🌐 Device
- Desktop
- OS: Windows 11
- Browser: Edge
- Browser Version: 111.0.1661.39

# ❌ Erro
1. Estilo dos textos do gráfico não compatível com UI.
2. Adicionar botões para filtrar tempo do histórico.

# 🔧 Correção
Que os valores para métrica possuam UI compatível e botões para filtrar histórico.

# 🌆 Screenshot
![image](https://user-images.githubusercontent.com/127423928/225348471-4fd035cb-5a72-445c-a1fb-c47a1a49b1d8.png)

**Comment by wesleyallan** [comment]
# 🔎 Analyze
Adicionar botões para filtro para grafíco.
